@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo":"66d2acc7c747bb46a889c9f4",
  "postId": "66d2acedc747bb46a889c9fa",
  "comment": "my first comment5",
    "profilePicture":"https://res.cloudinary.com/dhcw9nswr/image/upload/v1712197100/660e0de132ced657c4108512"

}

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/6621b1eaf8b49930cfd6d1a0
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/6621b1eaf8b49930cfd6d1a0/6621b1eaf8b49930cfd6d1a0
Content-Type: application/json
Accept: application/json
withCredentials: true
